# Limine v8 Configuration — Folkering DAQ Edition (aarch64)
# Target: Raspberry Pi 5 (BCM2712, Cortex-A76)

timeout: 0
verbose: yes
serial: yes
default_entry: 1

/ Folkering DAQ
    protocol: limine
    kernel_path: boot():/boot/kernel.elf
    cmdline: loglevel=debug
    kaslr: no
